AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DBName:
    Type: String
    Default: 'FastapiCloudFormation'
  DBUser:
    Type: String
    Default: 'admin'
  DBPassword:
    Type: String
    NoEcho: true
  DBInstanceClass:
    Type: String
    Default: 'db.t3.micro'
  DBAllocatedStorage:
    Type: Number
    Default: 20

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: 'subnet-group-db'
      DBSubnetGroupDescription: 'Grupo de subredes para RDS'
      SubnetIds:
        - !ImportValue MyPublicSubnetId
        - !ImportValue MyPublicSubnet2Id

  MySQLDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: 'Fastapi-rds-mysql'
      DBName: !Ref DBName
      Engine: 'mysql'
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      VPCSecurityGroups:
        - !ImportValue MyECSInstanceSecurityGroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      BackupRetentionPeriod: 7

Outputs:
  RDSMySQLEndpoint:
    Description: 'Endpoint de la base de datos RDS'
    Value: !GetAtt MySQLDatabase.Endpoint.Address
    Export:
      Name: RDSMySQLEndpoint
